'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'

type Scrim={id:string;title:string;game:string;category:string;entryFee:number;prizePool:number;totalSlots:number;status:string;startTime:string;_count:{registrations:number}}
type Reg={id:string;code:string;amount:number;paymentStatus:string;slotNumber:number|null;user:{name:string;email:string;ign:string|null};scrim:{title:string}}
const statuses=['DRAFT','OPEN','FULL','CLOSED','LIVE','COMPLETED','CANCELLED']

export default function AdminClient(){
 const [data,setData]=useState<{metrics:{activeScrims:number;todayRegistrations:number;confirmedPayments:number;pendingPayments:number};scrims:Scrim[]}|null>(null)
 const [regs,setRegs]=useState<Reg[]>([]); const [error,setError]=useState(''); const [showCreate,setShowCreate]=useState(false); const [busy,setBusy]=useState('')
 const [form,setForm]=useState({title:'',game:'Free Fire',category:'LW SOLO PAID',description:'',rules:'',date:'',startTime:'',registrationDeadline:'',entryFee:'15',prizePool:'250',totalSlots:'24'})
 const [cred,setCred]=useState<{id:string;roomId:string;roomPassword:string}|null>(null)
 const load=async()=>{const r=await fetch('/api/admin/dashboard');const d=await r.json();if(!r.ok){setError(d.error||'Unable to load admin console.');return}setData(d)}
 const loadRegs=async()=>{const r=await fetch('/api/admin/registrations');const d=await r.json();if(r.ok)setRegs(d.registrations)}
 useEffect(()=>{load();loadRegs()},[])
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy('create');setError('');const payload={...form,entryFee:Number(form.entryFee),prizePool:Number(form.prizePool),totalSlots:Number(form.totalSlots),date:new Date(form.date).toISOString(),startTime:new Date(form.startTime||form.date).toISOString(),registrationDeadline:new Date(form.registrationDeadline).toISOString()};const r=await fetch('/api/admin/scrims',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)setError(d.error||'Create failed');else{setShowCreate(false);await load()}setBusy('')}
 const updateStatus=async(id:string,status:string)=>{setBusy(`status-${id}`);setError('');const r=await fetch(`/api/admin/scrims/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const d=await r.json();if(!r.ok)setError(d.error||'Status update failed');else await load();setBusy('')}
 const cancel=async(id:string)=>{if(!confirm('Cancel this scrim? Refunds are manual.'))return;setBusy(id);const r=await fetch(`/api/admin/scrims/${id}`,{method:'DELETE'});if(!r.ok){const d=await r.json();setError(d.error||'Cancel failed')}else await load();setBusy('')}
 const publish=async(e:React.FormEvent)=>{e.preventDefault();if(!cred)return;setBusy('cred');const r=await fetch(`/api/admin/scrims/${cred.id}/credentials`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:cred.roomId,roomPassword:cred.roomPassword})});if(!r.ok){const d=await r.json();setError(d.error||'Publish failed')}else setCred(null);setBusy('')}
 const refund=async(id:string)=>{if(!confirm('Mark this payment as manually refunded?'))return;setBusy(id);const r=await fetch(`/api/admin/registrations/${id}/refund`,{method:'POST'});if(!r.ok){const d=await r.json();setError(d.error||'Refund failed')}await loadRegs();await load();setBusy('')}
 return <main><nav className="nav"><Link href="/" className="brand"><span>K</span> KRAVYADA <b>ESPORTS</b></Link><span className="adminpill">ADMIN CONSOLE</span><button className="login" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}}>LOGOUT</button></nav><section className="admin"><div className="sectionhead"><div><p className="eyebrow">CONTROL CENTER</p><h1>Operations Dashboard</h1></div><button className="btn primary" onClick={()=>setShowCreate(!showCreate)}>+ CREATE SCRIM</button></div>{error&&<p className="error">{error}</p>}{data&&<div className="metrics"><div><small>ACTIVE SCRIMS</small><strong>{data.metrics.activeScrims}</strong></div><div><small>TODAY'S REGISTRATIONS</small><strong>{data.metrics.todayRegistrations}</strong></div><div><small>CONFIRMED PAYMENTS</small><strong>₹{data.metrics.confirmedPayments}</strong></div><div><small>PENDING REVIEW</small><strong>{data.metrics.pendingPayments}</strong></div></div>}{showCreate&&<div className="adminpanel"><h2>Create Scrim</h2><form className="gridform" onSubmit={create}><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Game<input value={form.game} onChange={e=>setForm({...form,game:e.target.value})} required/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/></label><label>Entry fee (₹)<input type="number" min="0" value={form.entryFee} onChange={e=>setForm({...form,entryFee:e.target.value})} required/></label><label>Prize pool (₹)<input type="number" min="0" value={form.prizePool} onChange={e=>setForm({...form,prizePool:e.target.value})} required/></label><label>Total slots<input type="number" min="1" value={form.totalSlots} onChange={e=>setForm({...form,totalSlots:e.target.value})} required/></label><label>Date & time<input type="datetime-local" value={form.date} onChange={e=>setForm({...form,date:e.target.value,startTime:e.target.value})} required/></label><label>Registration deadline<input type="datetime-local" value={form.registrationDeadline} onChange={e=>setForm({...form,registrationDeadline:e.target.value})} required/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Rules<textarea value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})}/></label><button className="btn primary full" disabled={busy==='create'}>{busy==='create'?'CREATING...':'CREATE DRAFT →'}</button></form></div>}
 <div className="adminpanel"><div className="row"><h2>Scrim Management</h2><span className="muted">Full lifecycle control</span></div><div className="table"><div className="tr th"><span>SCRIM</span><span>GAME / MODE</span><span>SLOTS</span><span>STATUS</span><span>ACTION</span></div>{data?.scrims.map(s=><div className="tr" key={s.id}><span><b>{s.title}</b><small>{new Date(s.startTime).toLocaleString()}</small></span><span>{s.game} • {s.category}</span><span>{s._count.registrations}/{s.totalSlots}</span><span><select value={s.status} onChange={e=>updateStatus(s.id,e.target.value)} disabled={busy===`status-${s.id}`}>{statuses.map(x=><option key={x}>{x}</option>)}</select></span><span><button onClick={()=>setCred({id:s.id,roomId:'',roomPassword:''})}>🔐</button> <button onClick={()=>cancel(s.id)} disabled={busy===s.id}>CANCEL</button></span></div>)}</div></div>
 {cred&&<div className="adminpanel"><div className="row"><h2>Publish Match Credentials</h2><button onClick={()=>setCred(null)}>×</button></div><form className="gridform" onSubmit={publish}><label>Room ID<input value={cred.roomId} onChange={e=>setCred({...cred,roomId:e.target.value})} required/></label><label>Room Password<input value={cred.roomPassword} onChange={e=>setCred({...cred,roomPassword:e.target.value})} required/></label><button className="btn primary full" disabled={busy==='cred'}>{busy==='cred'?'PUBLISHING...':'PUBLISH TO PAID PLAYERS →'}</button></form></div>}
 <div className="adminpanel"><div className="row"><h2>Registrations & Payments</h2><span className="muted">Manual refund workflow</span></div><div className="table"><div className="tr th"><span>PLAYER</span><span>SCRIM</span><span>PAYMENT</span><span>CODE</span><span>ACTION</span></div>{regs.map(r=><div className="tr" key={r.id}><span><b>{r.user.name}</b><small>{r.user.ign||r.user.email}</small></span><span>{r.scrim.title}</span><span>{r.paymentStatus} • ₹{r.amount}</span><span>{r.code}</span><button onClick={()=>refund(r.id)} disabled={r.paymentStatus!=='PAID'||busy===r.id}>REFUND</button></div>)}</div></div>
 </section></main>
}
