'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'

type Scrim={id:string;title:string;game:string;category:string;entryFee:number;prizePool:number;totalSlots:number;status:string;startTime:string;_count:{registrations:number}}
const categories=['LW SOLO PAID','CS PAID 4v4','BR SCRIMS 4v4','DUO PAID','SOLO PAID']
export default function Home(){
 const [scrims,setScrims]=useState<Scrim[]>([]); const [filter,setFilter]=useState('ALL')
 useEffect(()=>{fetch('/api/scrims').then(r=>r.json()).then(d=>setScrims(d.scrims||[]))},[])
 const shown=scrims.filter(s=>filter==='ALL'||s.category===filter)
 return <main><nav className="nav"><Link href="/" className="brand"><span>K</span> KRAVYADA <b>ESPORTS</b></Link><div className="navlinks"><Link href="#scrims">Scrims</Link><Link href="#games">Games</Link><Link href="/dashboard">My Matches</Link><Link href="/login" className="login">Login</Link></div></nav><section className="hero"><div className="glow"/><p className="eyebrow">OFFICIAL KRAVYADA ESPORTS PLATFORM</p><h1>COMPETE.<br/><em>CONQUER.</em><br/>CLAIM YOUR PLACE.</h1><p className="sub">Paid scrims. Competitive rooms. Instant access to the matches you actually want to play.</p><div className="actions"><Link href="#scrims" className="btn primary">EXPLORE SCRIMS →</Link><Link href="/register" className="btn ghost">CREATE ACCOUNT</Link></div><div className="heroStats"><span><b>FREE FIRE</b> ACTIVE</span><span><b>SECURE</b> PAYMENTS</span><span><b>PAID PLAYERS</b> ONLY ROOM ACCESS</span></div></section><section id="games" className="section"><div className="sectionhead"><div><p className="eyebrow">CHOOSE YOUR BATTLE</p><h2>Games & Categories</h2></div></div><div className="games"><div className="game active"><small>01</small><h3>FREE FIRE</h3><p>LW Solo • CS 4v4 • BR 4v4 • Duo • Solo</p></div><div className="game"><small>02</small><h3>BGMI</h3><p>Coming soon</p></div><div className="game"><small>03</small><h3>CHESS</h3><p>Coming soon</p></div></div></section><section id="scrims" className="section scrimsection"><div className="sectionhead"><div><p className="eyebrow">OPEN REGISTRATIONS</p><h2>Upcoming Scrims</h2></div><span className="live">● LIVE REGISTRATION</span></div><div className="filters"><button className={filter==='ALL'?'selected':''} onClick={()=>setFilter('ALL')}>ALL</button>{categories.map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="cards">{shown.length===0?<div className="empty adminpanel"><h3>No scrims in this category.</h3><p className="muted">New KRAVYADA rooms will appear here when registration opens.</p></div>:shown.map(s=><article className="card" key={s.id}><div className="banner"><span>{s.game.toUpperCase()}</span><strong>{s.category}</strong></div><div className="cardbody"><div className="row"><h3>{s.title}</h3><span className="open">{s.status}</span></div><p className="time">◷ {new Date(s.startTime).toLocaleString()}</p><div className="stats"><div><small>ENTRY</small><b>₹{s.entryFee}</b></div><div><small>PRIZE POOL</small><b>₹{s.prizePool}</b></div><div><small>SLOTS</small><b>{s._count.registrations}/{s.totalSlots}</b></div></div><Link href={`/scrims/${s.id}`} className="cardbtn">REGISTER / VIEW DETAILS →</Link></div></article>)}</div></section><footer><div className="brand"><span>K</span> KRAVYADA <b>ESPORTS</b></div><p>COMPETE WITH PURPOSE.</p></footer></main>
}
