'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useParams,useRouter } from 'next/navigation'

type Scrim={id:string;title:string;game:string;category:string;description:string|null;rules:string|null;bannerUrl:string|null;date:string;startTime:string;registrationDeadline:string;entryFee:number;prizePool:number;totalSlots:number;status:string;remainingSlots:number}
export default function ScrimDetail(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [scrim,setScrim]=useState<Scrim|null>(null); const [slot,setSlot]=useState(''); const [team,setTeam]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [ok,setOk]=useState('')
 useEffect(()=>{fetch(`/api/scrims/${id}`).then(async r=>{const d=await r.json();if(r.ok)setScrim(d.scrim);else setError(d.error||'Scrim not found.')})},[id])
 const register=async()=>{setBusy(true);setError('');setOk('');const r=await fetch('/api/registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scrimId:id,slotNumber:slot?Number(slot):undefined,teamName:team||undefined})});const d=await r.json();if(r.status===401){router.push(`/login?next=/scrims/${id}`);return}if(!r.ok){setError(d.error||'Registration failed.');setBusy(false);return}setOk(`Registration ${d.registration.code} created. Opening payment...`);const p=await fetch('/api/payments/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({registrationId:d.registration.id})});const pd=await p.json();if(pd.url)window.location.href=pd.url;else{setError(pd.error||'Payment could not be started.');setBusy(false)}}
 if(!scrim)return <main><nav className="nav"><Link href="/" className="brand"><span>K</span> KRAVYADA <b>ESPORTS</b></Link></nav><section className="admin"><p className="muted">{error||'Loading scrim...'}</p></section></main>
 return <main><nav className="nav"><Link href="/" className="brand"><span>K</span> KRAVYADA <b>ESPORTS</b></Link><Link href="/" className="login">← ALL SCRIMS</Link></nav><section className="admin"><p className="eyebrow">{scrim.game} • {scrim.category}</p><h1>{scrim.title}</h1><p className="muted">{scrim.description||'Official KRAVYADA ESPORTS paid scrim.'}</p><div className="metrics"><div><small>ENTRY</small><strong>₹{scrim.entryFee}</strong></div><div><small>PRIZE POOL</small><strong>₹{scrim.prizePool}</strong></div><div><small>SLOTS LEFT</small><strong>{scrim.remainingSlots}/{scrim.totalSlots}</strong></div><div><small>STATUS</small><strong>{scrim.status}</strong></div></div><div className="adminpanel"><h2>Match Details</h2><p><b>START:</b> {new Date(scrim.startTime).toLocaleString()}</p><p><b>REGISTRATION DEADLINE:</b> {new Date(scrim.registrationDeadline).toLocaleString()}</p>{scrim.rules&&<><h3>Rules</h3><p className="muted">{scrim.rules}</p></>}</div>{scrim.status==='OPEN'&&scrim.remainingSlots>0?<div className="adminpanel"><h2>Register & Pay</h2><label>Slot number (optional)<input value={slot} onChange={e=>setSlot(e.target.value)} type="number" min="1" max={scrim.totalSlots} placeholder="Choose your slot"/></label><label>Team name (optional)<input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Your team"/></label>{error&&<p className="error">{error}</p>}{ok&&<p>{ok}</p>}<button className="btn primary full" onClick={register} disabled={busy}>{busy?'PROCESSING...':`REGISTER & PAY ₹${scrim.entryFee} →`}</button></div>:<div className="adminpanel"><h2>Registration closed</h2><p className="muted">This scrim is currently {scrim.status.toLowerCase()} or full.</p></div>}</section></main>
}
